### ISSUE TITLE
Remove the unnecessary code

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Eigo-sensei#2]
This website is based off a template and therefore has a lot of unnecessary code please tackle the first issue before proceeding to this one. Issue 1 can be found here https://github.com/adlyloukil/Eigo-sensei/issues/1

**Comment by blazingeagle1002** [comment]
I would like to take up this task

**Comment by blazingeagle1002** [comment]
Removed unnecessary code in stylesheet. Refer to PR #11

**Comment by sachininfy** [comment]
I would like to take this task

**Comment by adlyloukil** [comment]
This issue is still open.

**Comment by adlyloukil** [comment]
This issue is still open.

**Comment by adlyloukil** [comment]
Issue closed
