### ISSUE TITLE
Scaling problem

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Eigo-sensei#23]
When the you restore down the webpage to a smaller window, the nav bar does not extend all the way down to the twitter icon it gets cuts off. Refer to the image below.

![window mode](https://user-images.githubusercontent.com/22683645/31947420-3ef9c51e-b90f-11e7-9e07-f34ad1fecc85.JPG)

**Comment by roseg43** [comment]
Taking a look at this. The simplest solution is most likely a max-height CSS media query adjusting the padding/margin on those navigation items.
