### ISSUE TITLE
Translate the other html file into Japanese

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Eigo-sensei#31]
If anybody is good at translating Japanese would appreciate if they can made edits to the index_jp.html file based off index.html.

**Comment by adlyloukil** [comment]
Thanks for your help @riverwell

**Comment by Kijimu7** [comment]
Are you still looking for to translate in English to Japanese?

**Comment by adlyloukil** [comment]
@Kijimu7  Yes I still need it translated if you refer to the index_jp.html file the file is in Japanese however maybe not the best grammar?

**Comment by adlyloukil** [comment]
Issue has now been solved.
