### ISSUE TITLE
Icons blocked in Google Chrome, How to fix "insecure content blocked this page is trying to load scripts from unauthenticated sources"

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Eigo-sensei#49]
My issue is that some of the icons on my website are blocked, it seems to be an issue with my scripting.  Any help would be much appreciated @GoogleChrome

**Error Message**

`insecure content blocked this page is trying to load scripts from unauthenticated sources`

**Console Error's from Google Chrome**

![Google Chrome Inspect Element Console](https://user-images.githubusercontent.com/22683645/44846818-7298b280-ac49-11e8-81cd-359b8efc5b0d.PNG)

- Mixed Content: The page at 'https://www.adlyloukil.jp/' was loaded over HTTPS, but requested an insecure stylesheet 'http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css'. This request has been blocked; the content must be served over HTTPS.

- Mixed Content: The page at 'https://www.adlyloukil.jp/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Grand+Hotel'. This request has been blocked; the content must be served over HTTPS.

- Uncaught ReferenceError: $st is not defined
   at common.js:263
 
- Mixed Content: The page at 'https://www.adlyloukil.jp/' was loaded over HTTPS, but requested an insecure stylesheet 'http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css'. This request has been blocked; the content must be served over HTTPS.

- Mixed Content: The page at 'https://www.adlyloukil.jp/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Grand+Hotel'. This request has been blocked; the content must be served over HTTPS.

https://developers.google.com/web/fundamentals/security/hacked/request_review

**Comment by adlyloukil** [comment]
### **Error Message**
![Error Message](https://user-images.githubusercontent.com/22683645/45252858-6ef5e180-b355-11e8-89f0-a0b0096cafa7.png)

### **Missing Icons**
![Missing Icons](https://user-images.githubusercontent.com/22683645/45252859-71583b80-b355-11e8-8c5f-fb219be96f53.png)

**Comment by zeb-stephen-downs** [comment]
@adlyloukil give this a try: https://github.com/adlyloukil/Eigo-sensei/pull/50

**Comment by adlyloukil** [comment]
Sorry for merging this so late @zeb-stephen-downs . I just want to again thank you for your kindness in solving my issue. I have followed you and I look forward to contributing further to open source with you in this upcoming Hacktoberfest.

Regards,

Adly.
