### ISSUE TITLE
Make the webpage responsive

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Eigo-sensei#6]
All the text and images are not responsive on mobile/tablet etc. I would appreciate if someone could make everything responsive.

**Comment by joshuafbarker** [comment]
I can do this one for you.

**Comment by joshuafbarker** [comment]
Everything looks responsive to me. Can you be a little more specific on what the issue is?

**Comment by adlyloukil** [comment]
@joshuafbarker you are indeed correct i'll close the issue thank you for your contributions, more issues have since developed which I would appreciate if you could take a look at.
